### PR TITLE
Make sure the redis installation is properly secured

### PR DESCRIPTION
**Pull request by jvanbaarsen**
/cc @michiels / @joshuajansen

### CODE REVIEW

**Comment by michiels** [comment]
Ok I think this works. But maybe it's best to be really explicit about this. So to say:

```
Secure your Redis connection and make it only accessible to local connections. Uncomment the following line from /etc/redis/6379.conf:

line
```

I think that providing a bash command is really handy but kind of hides the thing that is modified in the config, and I think users should be explicitly aware of this (especially the not so advanced users).

**Comment by jvanbaarsen** [comment]
@michiels The entire installation manual is just copy and paste without any explenation. I really would love to keep it that way. I can see we create a secondary document which explains the steps in a bit more detail.

**Comment by michiels** [comment]
Okay, do all the other stuff involve security measures like this? That's the distinction I was trying to make: be really explicit about the security critical things, and provide handy dandy commands for the rest of the "chores".

Your final call :)

**Comment by jvanbaarsen** [comment]
@michiels I'll create an issue so we can create a "security.md" file in the near future and explain all the stuff we do to secure your content, and also what you need to do yourselve

**Comment by jvanbaarsen** [comment]
I like the idea of being more explicit about security, but I don't feel the installation manual is the place for it

**Comment by michiels** [comment]
Allright. I just hope people read all the other documents. The installation manual usually is the first (and only thing) people look at. Maybe we can reference to the Security.MD once we have it. That would be a good compromise.

**Comment by jvanbaarsen** [comment]
:+1:

**Pull request merged**
